# test compose file for Dockerfile development purposes
services:
  space:
    image: spacemacs:ubuntu-test
    stdin_open: true
    tty: true
    user: root
    volumes:
      - .:/data
    environment:
      - DISPLAY=armadillo12:0
