# ==================================================================================================
#
# File        : Dockerfile
#
# Purpose     : Recipe for a working free ModelSIM Altera FPGA edition.
#
# Author(s)   : Samuele FAVAZZA (samuele.favazza@duagon.com)
# 
# =================================================================================================

FROM base


